### PR TITLE
Draft logo ideas

### PR DESCRIPTION
**Pull request by vardyb**
Some logo ideas for issue #2 .
Currently just using black and white with the helvetica font until we can discuss and agree on a colour scheme and font choices.  I've also tried to keep it very simple so that it can work with a flat css framework like material design (materialize).

### CODE REVIEW

**Review by FedericoEsparza — COMMENTED** [review]
@vardyb Excellent work, Brent!
 
Great ideas.
 
Thanks for taking the time to provide a few choices.

I think I like the top row the best.
 
The standalone chalice/trophy with the "C" could function as a smaller, icon logo.
 
Would you mind trying to replace the first letter "C" in the very top left "CHAMPIONER" version with that trophy logo?
 
And if it's not too much trouble, you think you could try it with the original font, Fenix?

 
Thanks again, for your work.

**Comment by vardyb** [comment]
@FedericoEsparza  will make the discussed changes once I'm back from my holiday

**Comment by vardyb** [comment]
@FedericoEsparza I've made some changes to the logo ideas as per your comments above.

**Review by FedericoEsparza — APPROVED** [review]
Awesome job, @vardyb!

**Pull request merged**
