### PR TITLE
Updated hound to latest version from github

### PR DESCRIPTION
**Pull request by dkuku**
I updated all the packages and used latest master from github where headless chromedriver is fixed !

### CODE REVIEW

**Comment by FedericoEsparza** [comment]
@dkuku Fixes #114 Let me take it for a "test" drive, right now!

**Review by FedericoEsparza — APPROVED** [review]
@dkuku Amazing work, Daniel! 
Great job tracking down the solution!!
 
I just tested it 4 times, locally, in my terminal and in VSCode, including twice with your switching to the ref (commit)--that made it even better!
 
I'm going to go ahead and merge it, especially because @okothkongo1 might start work on #115 any time, now; and it has more tests to add to the test suite.
 
Thanks so much, Daniel!

**Comment by dkuku** [comment]
@FedericoEsparza You're welcome

**Comment by FedericoEsparza** [comment]
🏆

**Pull request merged**
