### PR TITLE
#3 Add Materializecss

### LINKED ISSUE #3: Create initial navbar version with Materialize
[http://materializecss.com/navbar.html](http://materializecss.com/navbar.html)
 
Tabs would be:
 - Mission
 - Volunteer
 - Donate
 - Products
 - Partners
 - Contact

### PR DESCRIPTION
**Pull request by 3fernandez**
closes #3

### CODE REVIEW

**Review by FedericoEsparza — CHANGES_REQUESTED** [review]
Looks great, @3fernandez! Outstanding work. 
 
There's just the issue of Node-Sass 3.8.0 not being friendly with Node 8 or above, so we need to force the Node-Sass dependency to be a more recent version. 
 
It's probably easiest to just add it as a direct dependency. Please make sure you can then run the app/server on Node 8.9.4 
 
I switched to Node 7.10 to unblock and run the app to see your changes. 
  
See here for more info: https://github.com/sass/node-sass/issues/2049
 
Let me know if you have any questions.

**Comment by 3fernandez** [comment]
Hey @FedericoEsparza, I don't know what's really happening. But I could install **node-sass** `v 3.8.0` for both **nodejs** `v 8.11.1` (which is globally setup in my environment) and `v 8.9.4` (just for troubleshooting purposes) and worked without any error. 🤔

So, do you need me to switch to **node** `v 7.10`?

**Comment by FedericoEsparza** [comment]
@3fernandez No, we should not downgrade to Node 7. We should stay on 8.9.4 because it's one of the latest LTS versions.
 
The problem for me is that the PR requires `node-sass 3.8.0` for **sass-brunch** in the `package-lock.json`:

 
Causing an npm postinstall failure/error:

 
I tried adding `node-sass 4.9.0` directly via `npm i node-sass@4.9.0 --save-dev`, but the `package-lock.json` file still tried to force the 3.8.0 install, giving the same failure.
 
What fixed it was going into `package-lock.json` and manually modifying the `sass-brunch` "require" of `node-sass` version from `3.8.0` to `4.5.3` and then running `npm i`, which had the weird effect of just removing the node-sass requirement from `sass-brunch`, but at least it fixed it:

 
And it runs now on 8.9.4:

 
So if you want to just repeat those 2 steps:

In `package-lock.json`,
1) manually modifying the `sass-brunch` "require" of `node-sass` version from `3.8.0` to `4.5.3,` and
2) then running `npm i`

then commit and push up to the PR branch, I'll pull it down and double-check that it runs.

**Comment by FedericoEsparza** [comment]
@3fernandez I added two additional steps, because running the server quietly complains about not having `node-sass`:

 
In `package-lock.json`,
1) manually modify the `sass-brunch` "require" of `node-sass` version from `3.8.0` to `4.5.3,` and
2) then while in `championer_one/assets` run `npm i`
3) followed by `rm -R node_modules` 
4) and finally `npm i node-sass@4.9.0 --save-dev`
 
then commit and push up to the PR branch, and I'll pull it down and double-check that it runs.

**Review by FedericoEsparza — APPROVED** [review]
Looks great! 
 
 
No more server complaints.
 
Will merge. Thanks Euclides.

**Pull request merged**
