### PR TITLE
add npm audit

### LINKED ISSUE #101: Add npm audit to travis CI
Add `npm audit` to our travis scripts after `- mix credo`.
Will require changing directories, so `- cd assets && npm audit` should work.

### PR DESCRIPTION
**Pull request by justudin**
Fixes #101

### CODE REVIEW

**Comment by FedericoEsparza** [comment]
@justudin Thanks so much for working on this, right away.
 
The reason it's failing is because Travis is running version 3.3 of npm, and 6.1.0 is required for npm audit.
 
```
before_install: 
 - npm i -g npm@6.1.0
```
You may also need to install the version of node that we're using 8.9.4, but you might try this first.

**Comment by justudin** [comment]
Yes, you're right @FedericoEsparza ! How stupid I am.. 
Thanks, it's work now after updating the npm version of Travis.

**Comment by FedericoEsparza** [comment]
@justudin Hey, you found a different solution on your own (as I was posting my last comment), so I'd say you're pretty smart!
 
Thanks for getting this done for us!

**Review by FedericoEsparza — APPROVED** [review]
@justudin Great job! Looks good.
 
I'll go ahead and merge.
 
You're welcome to join us at [agileventures.org](https://www.agileventures.org/users/sign_up), as we continue to build the site, and work on building other open source Elixir/Phoenix/React projects. 
 
If you sign up via your github account, you'll get an invitation to our Slack. Here's our team's [AgileVentures.org Slack channel](https://agileventures.slack.com/messages/phoenix_one)
 
Thanks again!

**Comment by justudin** [comment]
@FedericoEsparza Thanks a lot! 
Love to join the site.

**Pull request merged**
