### PR TITLE
Add 'mix test' as the last script step on travis.

### LINKED ISSUE #51: Mix credo blocking mix test on travis
We added`mix credo` to the `script:` field in the `.travis.yml` file.
 
It appears that it effectively now only runs `mix credo`:

mix credo on travis
mix credo on travis
 
`mix test` is the default script that appears to get overwritten when you add scripts explicitly. (https://docs.travis-ci.com/user/languages/elixir)
 
So the solution is probably as simple as adding `mix test` below `mix credo`.
 
We should be seeing this, as well as the credo output:

mix test on travis
mix test on travis
 
Link to build history: https://travis-ci.org/championer-org/championer_one/builds

### PR DESCRIPTION
**Pull request by 3fernandez**
Resolves #51

### CODE REVIEW

**Review by FedericoEsparza — APPROVED** [review]
Thanks, @3fernandez 👍 

 Really appreciate you taking care of this right away! 😅

**Comment by FedericoEsparza** [comment]
@3fernandez It worked right off the bat:
https://travis-ci.org/championer-org/championer_one/builds/390250165

**Comment by 3fernandez** [comment]
Yeah, I made sure of that before submit the PR. 😅

**Comment by FedericoEsparza** [comment]
Excellent 👍 
 
I made sure of it before I merged the PR 😆

**Pull request merged**
